"""create source and balance tables

Revision ID: 1a94810e8cff
Revises: 
Create Date: 2026-03-07 21:39:28.940742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a94810e8cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('key_owner', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_api_key_source_id'), 'api_key_source', ['id'], unique=False)
    op.create_table('balance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('usage_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['api_key_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_record_checked_at'), 'balance_record', ['checked_at'], unique=False)
    op.create_index(op.f('ix_balance_record_id'), 'balance_record', ['id'], unique=False)
    op.create_index(op.f('ix_balance_record_source_id'), 'balance_record', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_record_source_id'), table_name='balance_record')
    op.drop_index(op.f('ix_balance_record_id'), table_name='balance_record')
    op.drop_index(op.f('ix_balance_record_checked_at'), table_name='balance_record')
    op.drop_table('balance_record')
    op.drop_index(op.f('ix_api_key_source_id'), table_name='api_key_source')
    op.drop_table('api_key_source')
    # ### end Alembic commands ###
